// File Created - YAN WEIDONG A0258151H
/**
 * NOTE: The following tests are generated by AI based on user provided scenario plan.
 */
import mongoose from "mongoose";
import { orderStatusController } from "./authController.js";
import orderModel from "../models/orderModel.js";
import {
  DEFAULT_ORDER_STATUS,
  ORDER_STATUS_LIST,
} from "../constants/orderStatus.js";

jest.mock("../models/orderModel.js", () => ({
  find: jest.fn().mockReturnThis(),
  populate: jest.fn().mockReturnThis(),
  sort: jest.fn().mockReturnThis(),
  exec: jest.fn(),
  then: jest.fn((resolve) => resolve([])),
  findByIdAndUpdate: jest.fn(),
}));

/**
 * Unit Tests for orderStatusController
 *
 * Tests the order status update logic including:
 * - Successful update of an order's status.
 * - Validation for invalid orderId format.
 * - Validation for missing order status.
 * - Validation for invalid order status (not in ORDER_STATUS_LIST).
 * - Handling when the order is not found.
 * - Comprehensive error handling for database operations.
 *
 * Coverage Target: 100% (lines + functions)
 * Test Strategy: Output-based + Communication-based testing
 *
 * Test Doubles Used:
 * - orderModel.findByIdAndUpdate:    STUB (returns updated order or null)
 * - mongoose.Types.ObjectId.isValid: STUB (controls orderId format validation)
 * - req/res:                         FAKE (test doubles for Express request/response objects)
 *
 * Testing Techniques Applied:
 * - Happy Path: Valid inputs leading to success
 * - Negative Testing: Invalid inputs, edge cases, error conditions
 * - Equivalence Partitioning (EP): Valid/invalid orderId, valid/invalid status
 * - Interaction Testing: Verifying `orderModel` methods are called with correct arguments, console.log for errors
 *
 * Scenario Plan:
 * #  | Category             | Technique             | Scenario                                          | Expected Result
 * ---|----------------------|-----------------------|---------------------------------------------------|-----------------------------------------------------
 * 1  | Happy Path           | —                     | Valid orderId and valid status provided           | 200 Success, returns updated order
 * 2  | Validation           | Negative/EP           | Invalid orderId format (not a valid ObjectId)     | 400 Bad Request, "Invalid Order ID format"
 * 3  | Validation           | Negative/EP           | Missing status in req.body                        | 400 Bad Request, "Invalid or missing order status"
 * 4  | Validation           | Negative/EP           | Invalid status (not in ORDER_STATUS_LIST)         | 400 Bad Request, "Invalid or missing order status"
 * 5  | Order Not Found      | Negative              | orderModel.findByIdAndUpdate returns null         | 404 Not Found, "Order not found"
 * 6  | Error Handling       | Negative              | orderModel.findByIdAndUpdate rejects              | 500 Internal Server Error, "An error occurred...", error logged
 * 7  | Side Effects         | Interaction           | console.log called on error                       | console.log called with error message
 */
describe("orderStatusController", () => {
  let req, res, consoleSpy;
  const mockOrderId = "60c72b2f9b1d4b0015b2e3e6"; // A fake valid ObjectId string
  let mockValidStatus;
  let mockUpdatedOrder;

  beforeEach(() => {
    jest.clearAllMocks();

    mockValidStatus = DEFAULT_ORDER_STATUS; // "Not Processed"
    mockUpdatedOrder = {
      _id: mockOrderId,
      status: mockValidStatus,
      buyer: "someUserId",
      products: [],
    };

    req = {
      params: { orderId: mockOrderId },
      body: { status: mockValidStatus },
    };
    res = {
      status: jest.fn().mockReturnThis(),
      send: jest.fn(),
      json: jest.fn(),
    };
    jest.spyOn(mongoose.Types.ObjectId, "isValid").mockReturnValue(true);
    consoleSpy = jest.spyOn(console, "log").mockImplementation(() => {});

    // Default mocks for a successful path
    mongoose.Types.ObjectId.isValid.mockReturnValue(true);
    orderModel.findByIdAndUpdate.mockResolvedValue(mockUpdatedOrder); // Use the assigned mockUpdatedOrder
  });

  afterEach(() => {
    jest.restoreAllMocks();
    consoleSpy.mockRestore(); // Restore console.log after each test
  });

  describe("Happy Path", () => {
    it("should update order status successfully and return 200", async () => {
      // ── ARRANGE ──────────────────────────────────
      // (Defaults already set in beforeEach)

      // ── ACT ──────────────────────────────────────
      await orderStatusController(req, res);

      // ── ASSERT ───────────────────────────────────
      expect(mongoose.Types.ObjectId.isValid).toHaveBeenCalledWith(mockOrderId);
      expect(orderModel.findByIdAndUpdate).toHaveBeenCalledWith(
        mockOrderId,
        { status: mockValidStatus },
        { new: true },
      );
      expect(res.status).toHaveBeenCalledWith(200);
      expect(res.send).toHaveBeenCalledWith({
        success: true,
        message: "Order status updated successfully.",
        order: mockUpdatedOrder,
      });
      expect(consoleSpy).not.toHaveBeenCalled();
    });
  });

  describe("Validation", () => {
    it("should return 400 if orderId format is invalid", async () => {
      // ── ARRANGE ──────────────────────────────────
      mongoose.Types.ObjectId.isValid.mockReturnValue(false);
      req.params.orderId = "invalidId";

      // ── ACT ──────────────────────────────────────
      await orderStatusController(req, res);

      // ── ASSERT ───────────────────────────────────
      expect(mongoose.Types.ObjectId.isValid).toHaveBeenCalledWith("invalidId");
      expect(orderModel.findByIdAndUpdate).not.toHaveBeenCalled();
      expect(res.status).toHaveBeenCalledWith(400);
      expect(res.send).toHaveBeenCalledWith({
        success: false,
        message: "Invalid Order ID format. Please provide a valid ObjectId.",
      });
      expect(consoleSpy).not.toHaveBeenCalled();
    });

    it("should return 400 if status is missing from req.body", async () => {
      // ── ARRANGE ──────────────────────────────────
      req.body.status = undefined; // Missing status

      // ── ACT ──────────────────────────────────────
      await orderStatusController(req, res);

      // ── ASSERT ───────────────────────────────────
      expect(mongoose.Types.ObjectId.isValid).toHaveBeenCalledWith(mockOrderId);
      expect(orderModel.findByIdAndUpdate).not.toHaveBeenCalled();
      expect(res.status).toHaveBeenCalledWith(400);
      expect(res.send).toHaveBeenCalledWith({
        success: false,
        message: `Invalid or missing order status. Allowed values are: ${ORDER_STATUS_LIST.join(", ")}.`,
      });
      expect(consoleSpy).not.toHaveBeenCalled();
    });

    it("should reject invalid order status value", async () => {
      // ── ARRANGE ──────────────────────────────────
      req.body.status = "NonExistentStatus";

      // ── ACT ──────────────────────────────────────
      await orderStatusController(req, res);

      // ── ASSERT ───────────────────────────────────
      expect(res.status).toHaveBeenCalledWith(400);
      expect(res.send).toHaveBeenCalledWith(
        expect.objectContaining({
          success: false,
          message: expect.stringContaining("Invalid or missing order status"),
        }),
      );
    });
  });

  describe("Error Handling", () => {
    it("should return 404 if orderModel.findByIdAndUpdate returns null", async () => {
      // ── ARRANGE ──────────────────────────────────
      orderModel.findByIdAndUpdate.mockResolvedValue(null);

      // ── ACT ──────────────────────────────────────
      await orderStatusController(req, res);

      // ── ASSERT ───────────────────────────────────
      expect(mongoose.Types.ObjectId.isValid).toHaveBeenCalledWith(mockOrderId);
      expect(orderModel.findByIdAndUpdate).toHaveBeenCalledWith(
        mockOrderId,
        { status: mockValidStatus },
        { new: true },
      );
      expect(res.status).toHaveBeenCalledWith(404);
      expect(res.send).toHaveBeenCalledWith({
        success: false,
        message: "Order not found with the provided ID.",
      });
      expect(consoleSpy).not.toHaveBeenCalled();
    });

    it("should return 500 when database operation fails", async () => {
      // ── ARRANGE ──────────────────────────────────
      const dbError = new Error("Database update failed");
      orderModel.findByIdAndUpdate.mockRejectedValue(dbError);

      // ── ACT ──────────────────────────────────────
      await orderStatusController(req, res);

      // ── ASSERT ───────────────────────────────────
      expect(res.status).toHaveBeenCalledWith(500);
      expect(res.send).toHaveBeenCalledWith(
        expect.objectContaining({
          success: false,
          message: expect.stringContaining("error occurred while updating"),
        }),
      );
    });
  });
});
