// AI Policy : the following file is generated by AI
// Test cases written by: KIM SHI TONG A0265858J
/**
 * Integration Test: BE-INT-1
 * Author: Kim Shi Tong, A0265858J
 *
 * APPROACH: Bottom-up integration testing (Level 1)
 *
 * Level 0 (MS1 — done): Units tested in isolation with full mocking.
 * Level 1 (this file): Controllers integrated with REAL models + REAL database
 *   - registerController, loginController, forgotPasswordController
 *     integrated with REAL userModel + REAL authHelper (bcrypt) + REAL MongoDB
 *
 * What was mocked in MS1 that is NOW REAL:
 *   - userModel → real Mongoose model with mongodb-memory-server
 *   - hashPassword / comparePassword → real bcrypt operations
 *   - JWT.sign / JWT.verify → real JWT with test secret
 *
 * What stays mocked (and why):
 *   - Express req/res objects: We test at controller level (Level 1),
 *     not at route level (Level 2). req/res are just interfaces.
 *
 * Integration points tested:
 *   - registerController writes to userModel via real DB with real bcrypt hashing
 *   - loginController reads from userModel and uses real comparePassword (bcrypt)
 *   - forgotPasswordController updates password in real DB then loginController verifies
 *   - JWT tokens are real (signed with test secret)
 */

import mongoose from "mongoose";
import { MongoMemoryServer } from "mongodb-memory-server";
import {
  registerController,
  loginController,
  forgotPasswordController,
} from "../../controllers/authController.js";
import userModel from "../../models/userModel.js";
import { hashPassword } from "../../helpers/authHelper.js";

// Set JWT_SECRET for test environment
process.env.JWT_SECRET = "test-secret-key";

let mongoServer;

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  await mongoose.connect(mongoServer.getUri());
});

afterEach(async () => {
  const collections = mongoose.connection.collections;
  for (const key in collections) {
    await collections[key].deleteMany({});
  }
});

afterAll(async () => {
  await mongoose.connection.dropDatabase();
  await mongoose.connection.close();
  await mongoServer.stop();
});

/**
 * Creates mock Express req/res objects for controller-level testing.
 * We test controllers directly (Level 1) before testing routes (Level 2).
 */
const mockReq = (body = {}, params = {}) => ({
  body,
  params,
  user: null,
});

const mockRes = () => {
  const res = {};
  res.status = jest.fn().mockReturnValue(res);
  res.send = jest.fn().mockReturnValue(res);
  res.json = jest.fn().mockReturnValue(res);
  return res;
};

describe("BE-INT-1: Auth Controller ↔ User Model ↔ Auth Helper Integration", () => {
  // // Kim Shi Tong, A0265858J
  it("should register a user with real bcrypt hashing and persist in real DB", async () => {
    const req = mockReq({
      name: "John Doe",
      email: "john@test.com",
      password: "password123",
      phone: "12345678",
      address: "123 Street",
      answer: "fluffy",
    });
    const res = mockRes();

    await registerController(req, res);

    // 1. Response indicates success
    expect(res.status).toHaveBeenCalledWith(201);
    expect(res.send).toHaveBeenCalledWith(
      expect.objectContaining({ success: true })
    );

    // 2. User actually exists in the database
    const userInDB = await userModel.findOne({ email: "john@test.com" });
    expect(userInDB).not.toBeNull();
    expect(userInDB.name).toBe("John Doe");

    // 3. Password is hashed (NOT plaintext) — key integration point
    expect(userInDB.password).not.toBe("password123");
    expect(userInDB.password).toMatch(/^\$2[aby]?\$.+$/); // bcrypt hash pattern
  });

  // // Kim Shi Tong, A0265858J
  it("should reject registration with duplicate email via real DB lookup", async () => {
    // Create a user first using real model + real hashing
    await new userModel({
      name: "Existing",
      email: "john@test.com",
      password: await hashPassword("pass123"),
      phone: "111",
      address: "addr",
      answer: "ans",
    }).save();

    const req = mockReq({
      name: "John Again",
      email: "john@test.com", // same email
      password: "newpass",
      phone: "222",
      address: "addr2",
      answer: "ans2",
    });
    const res = mockRes();

    await registerController(req, res);

    expect(res.status).toHaveBeenCalledWith(409);
    expect(res.send).toHaveBeenCalledWith(
      expect.objectContaining({
        success: false,
        message: expect.stringContaining("Already"),
      })
    );
  });

  // // Kim Shi Tong, A0265858J
  it("should login with valid credentials after registration (register → login chain)", async () => {
    // Register a user first using the real controller (full integration)
    const regReq = mockReq({
      name: "John",
      email: "john@test.com",
      password: "password123",
      phone: "123",
      address: "addr",
      answer: "ans",
    });
    await registerController(regReq, mockRes());

    // Now attempt login
    const loginReq = mockReq({ email: "john@test.com", password: "password123" });
    const loginRes = mockRes();

    await loginController(loginReq, loginRes);

    expect(loginRes.status).toHaveBeenCalledWith(200);
    const responseData = loginRes.send.mock.calls[0][0];
    expect(responseData.success).toBe(true);
    expect(responseData.token).toBeDefined();
    expect(responseData.user.name).toBe("John");
    expect(responseData.user.email).toBe("john@test.com");
    // Token should be a valid JWT string (3 dot-separated parts)
    expect(responseData.token.split(".")).toHaveLength(3);
  });

  // // Kim Shi Tong, A0265858J
  it("should reject login with wrong password (real bcrypt comparison fails)", async () => {
    // Register user
    const regReq = mockReq({
      name: "John",
      email: "john@test.com",
      password: "password123",
      phone: "123",
      address: "addr",
      answer: "ans",
    });
    await registerController(regReq, mockRes());

    // Login with wrong password
    const loginReq = mockReq({ email: "john@test.com", password: "WRONG" });
    const loginRes = mockRes();

    await loginController(loginReq, loginRes);

    expect(loginRes.status).toHaveBeenCalledWith(401);
    expect(loginRes.send).toHaveBeenCalledWith(
      expect.objectContaining({
        success: false,
        message: "Invalid Password",
      })
    );
  });

  // // Kim Shi Tong, A0265858J
  it("should reset password then login with new password (register → forgot → login chain)", async () => {
    // Step 1: Register user
    await registerController(
      mockReq({
        name: "John",
        email: "john@test.com",
        password: "oldpass123",
        phone: "123",
        address: "addr",
        answer: "fluffy",
      }),
      mockRes()
    );

    // Step 2: Reset password
    const resetReq = mockReq({
      email: "john@test.com",
      answer: "fluffy",
      newPassword: "newpass456",
    });
    const resetRes = mockRes();
    await forgotPasswordController(resetReq, resetRes);
    expect(resetRes.status).toHaveBeenCalledWith(200);
    expect(resetRes.send).toHaveBeenCalledWith(
      expect.objectContaining({ success: true })
    );

    // Step 3: Login with NEW password should succeed
    const newLoginRes = mockRes();
    await loginController(
      mockReq({ email: "john@test.com", password: "newpass456" }),
      newLoginRes
    );
    expect(newLoginRes.send.mock.calls[0][0].success).toBe(true);

    // Step 4: Login with OLD password should fail
    const oldLoginRes = mockRes();
    await loginController(
      mockReq({ email: "john@test.com", password: "oldpass123" }),
      oldLoginRes
    );
    expect(oldLoginRes.send.mock.calls[0][0].success).toBe(false);
  });

  // // Kim Shi Tong, A0265858J
  it("should reject login with non-existent email via real DB lookup", async () => {
    // No users in DB (afterEach clears it)
    const loginReq = mockReq({ email: "ghost@test.com", password: "pass123" });
    const loginRes = mockRes();

    await loginController(loginReq, loginRes);

    expect(loginRes.status).toHaveBeenCalledWith(404);
    expect(loginRes.send).toHaveBeenCalledWith(
      expect.objectContaining({
        success: false,
        message: expect.stringContaining("not registered"),
      })
    );
  });
});
