// AI Policy : the following file is generated by AI
// Test cases written by: KIM SHI TONG A0265858J
/**
 * Integration Test: FE-INT-2
 * Author: Kim Shi Tong, A0265858J
 *
 * ============================================================================
 * APPROACH (Rubric 0.5%): Bottom-up integration testing (Level 1)
 * ============================================================================
 * Level 0 (MS1 — done): Units tested in isolation with full mocking.
 * Level 1 (this file): Pages integrated with REAL context providers + REAL React Router.
 *   - Register.js and Login.js rendered in a real Routes tree
 *   - After successful registration, navigation to /login renders Login page
 *
 * Bottom-up rationale: Context providers (AuthProvider, CartProvider, SearchProvider)
 * are the lowest-level frontend modules. We integrate page components on top of
 * them, and test that navigation between pages works through real React Router.
 *
 * ============================================================================
 * CORRECTNESS (Rubric 1%): Real integration, not mocking in disguise
 * ============================================================================
 * What was mocked in MS1 that is NOW REAL:
 *   - useAuth context → now real AuthProvider
 *   - React Router navigation → real MemoryRouter with Routes
 *   - Register → Login page transition via real navigate()
 *
 * The test verifies the INTERFACE between Register and Login: Register calls
 * navigate("/login") on success → React Router renders Login.js at the new URL.
 * Two page components integrated via routing within a real provider tree.
 *
 * What stays mocked (and why — "mocks/stubs are appropriately used"):
 *   - axios: Frontend tests don't run a real backend server. The integration
 *     is between frontend pages via React Router, not frontend ↔ backend.
 *   - react-hot-toast: External UI notification library, not an integration point.
 *   - Layout: Simplified to avoid react-helmet complexity.
 *
 * ============================================================================
 * VARIETY (Rubric 0.5%): Multiple component files tested
 * ============================================================================
 * This file tests across 2 different source files:
 *   - pages/Auth/Register.js (form submission, navigates to /login on success)
 *   - pages/Auth/Login.js (destination page rendered after navigation)
 *
 * Integration points tested:
 *   - Register.js calls API → on success, calls navigate("/login")
 *   - React Router renders Login.js at /login path
 *   - Both pages work within the same real provider tree
 */

import React from "react";
import { render, screen, waitFor, act, fireEvent } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter, Routes, Route } from "react-router-dom";
import { AuthProvider } from "../../src/context/auth";
import { CartProvider } from "../../src/context/cart";
import { SearchProvider } from "../../src/context/search";
import Register from "../../src/pages/Auth/Register";
import Login from "../../src/pages/Auth/Login";
import axios from "axios";

// ONLY mock the network layer
jest.mock("axios");

// Mock toast
jest.mock("react-hot-toast", () => ({
  __esModule: true,
  default: {
    success: jest.fn(),
    error: jest.fn(),
  },
  Toaster: () => null,
}));

// Mock Layout to render children directly
jest.mock("../../src/components/Layout", () => {
  return function MockLayout({ children }) {
    return <div data-testid="layout">{children}</div>;
  };
});

beforeEach(() => {
  localStorage.clear();
  jest.clearAllMocks();

  // Default axios mock for any GET requests (e.g., category)
  axios.get.mockResolvedValue({
    data: { success: true, category: [] },
  });
});

afterEach(() => {
  localStorage.clear();
  jest.restoreAllMocks();
});

describe("FE-INT-2: Register → Login Navigation Integration", () => {
  let user;

  beforeEach(() => {
    user = userEvent.setup();
  });

  // // Kim Shi Tong, A0265858J
  it("should navigate from Register to Login page after successful registration", async () => {
    // Mock register API success
    axios.post.mockResolvedValueOnce({
      data: { success: true, message: "User registered successfully" },
    });

    await act(async () => {
      render(
        <AuthProvider>
          <CartProvider>
            <SearchProvider>
              <MemoryRouter initialEntries={["/register"]}>
                <Routes>
                  <Route path="/register" element={<Register />} />
                  <Route path="/login" element={<Login />} />
                </Routes>
              </MemoryRouter>
            </SearchProvider>
          </CartProvider>
        </AuthProvider>
      );
    });

    // Verify we start on Register page
    expect(screen.getByText("REGISTER FORM")).toBeInTheDocument();

    // Fill in registration form
    fireEvent.change(screen.getByPlaceholderText(/Enter Your Name/i), { target: { value: "John" } });
    fireEvent.change(screen.getByPlaceholderText(/Enter Your Email/i), { target: { value: "john@test.com" } });
    fireEvent.change(screen.getByPlaceholderText(/Enter Your Password/i), { target: { value: "password123" } });
    fireEvent.change(screen.getByPlaceholderText(/Enter Your Phone/i), { target: { value: "12345678" } });
    fireEvent.change(screen.getByPlaceholderText(/Enter Your Address/i), { target: { value: "123 Street" } });
    // DOB field
    fireEvent.change(screen.getByPlaceholderText(/Enter Your DOB/i), { target: { value: "2000-01-01" } });
    // Answer field
    fireEvent.change(screen.getByPlaceholderText(/What is Your Favorite sports/i), { target: { value: "fluffy" } });

    await act(async () => {
      fireEvent.click(screen.getByRole("button", { name: /REGISTER/i }));
    });

    // After navigation, the Login page should render
    await waitFor(() => {
      expect(screen.getByText("LOGIN FORM")).toBeInTheDocument();
      expect(screen.getByPlaceholderText(/Enter Your Email/i)).toBeInTheDocument();
      expect(screen.getByRole("button", { name: /LOGIN/i })).toBeInTheDocument();
    });
  });
});
